/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import caballero.practico6.DirectorioTelefonico;

/**
 *
 * @author Guido Caballero
 */
public class Escritorio extends javax.swing.JFrame {
    
    private static DirectorioTelefonico dr = new DirectorioTelefonico();
    
    /**
     * Creates new form Escritorio
     */
    public Escritorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdPantPrinc = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMInicio = new javax.swing.JMenu();
        jMNuevo = new javax.swing.JMenuItem();
        jMBuscar = new javax.swing.JMenuItem();
        jMEliminar = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdPantPrincLayout = new javax.swing.GroupLayout(jdPantPrinc);
        jdPantPrinc.setLayout(jdPantPrincLayout);
        jdPantPrincLayout.setHorizontalGroup(
            jdPantPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jdPantPrincLayout.setVerticalGroup(
            jdPantPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        jMInicio.setText("Menu");

        jMNuevo.setText("Nuevo");
        jMNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMNuevoActionPerformed(evt);
            }
        });
        jMInicio.add(jMNuevo);

        jMBuscar.setText("Buscar ");
        jMBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBuscarActionPerformed(evt);
            }
        });
        jMInicio.add(jMBuscar);

        jMEliminar.setText("Eiminar");
        jMEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMEliminarActionPerformed(evt);
            }
        });
        jMInicio.add(jMEliminar);

        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMInicio.add(jMSalir);

        jMenuBar1.add(jMInicio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdPantPrinc)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdPantPrinc)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMEliminarActionPerformed
        jdPantPrinc.removeAll();
        jdPantPrinc.repaint();
        ViewEliminar ve = new ViewEliminar();
        ve.setVisible(true);
        jdPantPrinc.add(ve);
        jdPantPrinc.moveToFront(ve);
    }//GEN-LAST:event_jMEliminarActionPerformed

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jMSalirActionPerformed

    private void jMNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMNuevoActionPerformed
        jdPantPrinc.removeAll();
        jdPantPrinc.repaint();
        ViewCarga vc = new ViewCarga();
        vc.setVisible(true);
        jdPantPrinc.add(vc);
        jdPantPrinc.moveToFront(vc);
    }//GEN-LAST:event_jMNuevoActionPerformed

    private void jMBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBuscarActionPerformed
        jdPantPrinc.removeAll();
        jdPantPrinc.repaint();
        ViewBuscar vb = new ViewBuscar();
        vb.setVisible(true);
        jdPantPrinc.add(vb);
        jdPantPrinc.moveToFront(vb);
    }//GEN-LAST:event_jMBuscarActionPerformed

    public static DirectorioTelefonico getDr() {
        return dr;
    }
    public static void setDr(DirectorioTelefonico dr) {
        Escritorio.dr = dr;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMBuscar;
    private javax.swing.JMenuItem jMEliminar;
    private javax.swing.JMenu jMInicio;
    private javax.swing.JMenuItem jMNuevo;
    private javax.swing.JMenuItem jMSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdPantPrinc;
    // End of variables declaration//GEN-END:variables
}
